### ISSUE TITLE
support HTTP/0.9

### ISSUE THREAD

**Issue by thutex** [svenstaro/dummyhttp#381]
even though it is ancient, there are still use-cases to debug HTTP/0.9 (looking at you, yealink....)
so support within dummyhttp would be amazing.

at the VERY least, a message saying "something came in, but i have no clue if it's http or not" would be appreciated,
as to not miss incoming requests when they are http/0.9

**Comment by svenstaro** [comment]
Hm it's not really my use case. However, I'd be happy about PRs for this. Would you like to try to contribute this?

**Comment by svenstaro** [comment]
I don't think this will be done. `hyper` doesn't seem to [support it](https://docs.rs/hyper-util/latest/hyper_util/server/conn/auto/struct.Builder.html) and I doubt it ever will.
